// Code generated by goctl. DO NOT EDIT!
// Source: guarantee_trade.proto

package server

import (
	"context"

	"github.com/bjhuang103/go_pay/guarantee_trade/guarantee_trade"
	"github.com/bjhuang103/go_pay/guarantee_trade/internal/logic"
	"github.com/bjhuang103/go_pay/guarantee_trade/internal/svc"
)

type GuaranteeTradeServer struct {
	svcCtx *svc.ServiceContext
}

func NewGuaranteeTradeServer(svcCtx *svc.ServiceContext) *GuaranteeTradeServer {
	return &GuaranteeTradeServer{
		svcCtx: svcCtx,
	}
}

func (s *GuaranteeTradeServer) PrePay(ctx context.Context, in *guarantee_trade.PrePayReq) (*guarantee_trade.PrePayResp, error) {
	l := logic.NewPrePayLogic(ctx, s.svcCtx)
	return l.PrePay(in)
}

func (s *GuaranteeTradeServer) Pay(ctx context.Context, in *guarantee_trade.PayReq) (*guarantee_trade.PayResp, error) {
	l := logic.NewPayLogic(ctx, s.svcCtx)
	return l.Pay(in)
}
