// Code generated by goctl. DO NOT EDIT!
// Source: guarantee_trade.proto

package main

import (
	"flag"
	"fmt"

	"github.com/bjhuang103/go_pay/guarantee_trade/guarantee_trade"
	"github.com/bjhuang103/go_pay/guarantee_trade/internal/config"
	"github.com/bjhuang103/go_pay/guarantee_trade/internal/server"
	"github.com/bjhuang103/go_pay/guarantee_trade/internal/svc"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/guaranteetrade.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	srv := server.NewGuaranteeTradeServer(ctx)

	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		guarantee_trade.RegisterGuaranteeTradeServer(grpcServer, srv)
	})
	defer s.Stop()

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
