// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/bjhuang103/go_pay/union_gateway/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/add",
				Handler: AddHandler(serverCtx),
			},
		},
	)
}
