// Code generated by goctl. DO NOT EDIT!
// Source: pay_core.proto

package main

import (
	"flag"
	"fmt"

	"github.com/bjhuang103/go_pay/pay_core/internal/config"
	"github.com/bjhuang103/go_pay/pay_core/internal/server"
	"github.com/bjhuang103/go_pay/pay_core/internal/svc"
	"github.com/bjhuang103/go_pay/pay_core/pay_core"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/paycore.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	srv := server.NewPayCoreServer(ctx)

	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		pay_core.RegisterPayCoreServer(grpcServer, srv)
	})
	defer s.Stop()

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
