// Code generated by goctl. DO NOT EDIT!
// Source: pay_core.proto

package server

import (
	"context"

	"github.com/bjhuang103/go_pay/pay_core/internal/logic"
	"github.com/bjhuang103/go_pay/pay_core/internal/svc"
	"github.com/bjhuang103/go_pay/pay_core/pay_core"
)

type PayCoreServer struct {
	svcCtx *svc.ServiceContext
}

func NewPayCoreServer(svcCtx *svc.ServiceContext) *PayCoreServer {
	return &PayCoreServer{
		svcCtx: svcCtx,
	}
}

func (s *PayCoreServer) Pay(ctx context.Context, in *pay_core.PayReq) (*pay_core.PayResp, error) {
	l := logic.NewPayLogic(ctx, s.svcCtx)
	return l.Pay(in)
}

func (s *PayCoreServer) Refund(ctx context.Context, in *pay_core.RefundReq) (*pay_core.RefundResp, error) {
	l := logic.NewRefundLogic(ctx, s.svcCtx)
	return l.Refund(in)
}
