// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: pay_core.proto

package pay_core

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradeNo string `protobuf:"bytes,1,opt,name=TradeNo,proto3" json:"TradeNo,omitempty"`
}

func (x *PayReq) Reset() {
	*x = PayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_core_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayReq) ProtoMessage() {}

func (x *PayReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_core_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayReq.ProtoReflect.Descriptor instead.
func (*PayReq) Descriptor() ([]byte, []int) {
	return file_pay_core_proto_rawDescGZIP(), []int{0}
}

func (x *PayReq) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

type PayResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode string `protobuf:"bytes,1,opt,name=RetCode,proto3" json:"RetCode,omitempty"`
}

func (x *PayResp) Reset() {
	*x = PayResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_core_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayResp) ProtoMessage() {}

func (x *PayResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_core_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayResp.ProtoReflect.Descriptor instead.
func (*PayResp) Descriptor() ([]byte, []int) {
	return file_pay_core_proto_rawDescGZIP(), []int{1}
}

func (x *PayResp) GetRetCode() string {
	if x != nil {
		return x.RetCode
	}
	return ""
}

type RefundReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradeNo string `protobuf:"bytes,1,opt,name=TradeNo,proto3" json:"TradeNo,omitempty"`
}

func (x *RefundReq) Reset() {
	*x = RefundReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_core_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundReq) ProtoMessage() {}

func (x *RefundReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_core_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundReq.ProtoReflect.Descriptor instead.
func (*RefundReq) Descriptor() ([]byte, []int) {
	return file_pay_core_proto_rawDescGZIP(), []int{2}
}

func (x *RefundReq) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

type RefundResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode string `protobuf:"bytes,1,opt,name=RetCode,proto3" json:"RetCode,omitempty"`
}

func (x *RefundResp) Reset() {
	*x = RefundResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_core_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResp) ProtoMessage() {}

func (x *RefundResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_core_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResp.ProtoReflect.Descriptor instead.
func (*RefundResp) Descriptor() ([]byte, []int) {
	return file_pay_core_proto_rawDescGZIP(), []int{3}
}

func (x *RefundResp) GetRetCode() string {
	if x != nil {
		return x.RetCode
	}
	return ""
}

var File_pay_core_proto protoreflect.FileDescriptor

var file_pay_core_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x61, 0x79, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x61, 0x79, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x22, 0x0a, 0x06, 0x70, 0x61,
	0x79, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x22, 0x23,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x74, 0x43,
	0x6f, 0x64, 0x65, 0x22, 0x25, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x22, 0x26, 0x0a, 0x0a, 0x72, 0x65,
	0x66, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x32, 0x6b, 0x0a, 0x08, 0x70, 0x61, 0x79, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x2a,
	0x0a, 0x03, 0x70, 0x61, 0x79, 0x12, 0x10, 0x2e, 0x70, 0x61, 0x79, 0x5f, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x70, 0x61, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x61, 0x79, 0x5f, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x70, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x06, 0x72, 0x65,
	0x66, 0x75, 0x6e, 0x64, 0x12, 0x13, 0x2e, 0x70, 0x61, 0x79, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x61, 0x79, 0x5f,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pay_core_proto_rawDescOnce sync.Once
	file_pay_core_proto_rawDescData = file_pay_core_proto_rawDesc
)

func file_pay_core_proto_rawDescGZIP() []byte {
	file_pay_core_proto_rawDescOnce.Do(func() {
		file_pay_core_proto_rawDescData = protoimpl.X.CompressGZIP(file_pay_core_proto_rawDescData)
	})
	return file_pay_core_proto_rawDescData
}

var file_pay_core_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pay_core_proto_goTypes = []interface{}{
	(*PayReq)(nil),     // 0: pay_core.payReq
	(*PayResp)(nil),    // 1: pay_core.payResp
	(*RefundReq)(nil),  // 2: pay_core.refundReq
	(*RefundResp)(nil), // 3: pay_core.refundResp
}
var file_pay_core_proto_depIdxs = []int32{
	0, // 0: pay_core.pay_core.pay:input_type -> pay_core.payReq
	2, // 1: pay_core.pay_core.refund:input_type -> pay_core.refundReq
	1, // 2: pay_core.pay_core.pay:output_type -> pay_core.payResp
	3, // 3: pay_core.pay_core.refund:output_type -> pay_core.refundResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pay_core_proto_init() }
func file_pay_core_proto_init() {
	if File_pay_core_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pay_core_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_core_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_core_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_core_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pay_core_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pay_core_proto_goTypes,
		DependencyIndexes: file_pay_core_proto_depIdxs,
		MessageInfos:      file_pay_core_proto_msgTypes,
	}.Build()
	File_pay_core_proto = out.File
	file_pay_core_proto_rawDesc = nil
	file_pay_core_proto_goTypes = nil
	file_pay_core_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PayCoreClient is the client API for PayCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PayCoreClient interface {
	Pay(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error)
	Refund(ctx context.Context, in *RefundReq, opts ...grpc.CallOption) (*RefundResp, error)
}

type payCoreClient struct {
	cc grpc.ClientConnInterface
}

func NewPayCoreClient(cc grpc.ClientConnInterface) PayCoreClient {
	return &payCoreClient{cc}
}

func (c *payCoreClient) Pay(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error) {
	out := new(PayResp)
	err := c.cc.Invoke(ctx, "/pay_core.pay_core/pay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payCoreClient) Refund(ctx context.Context, in *RefundReq, opts ...grpc.CallOption) (*RefundResp, error) {
	out := new(RefundResp)
	err := c.cc.Invoke(ctx, "/pay_core.pay_core/refund", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayCoreServer is the server API for PayCore service.
type PayCoreServer interface {
	Pay(context.Context, *PayReq) (*PayResp, error)
	Refund(context.Context, *RefundReq) (*RefundResp, error)
}

// UnimplementedPayCoreServer can be embedded to have forward compatible implementations.
type UnimplementedPayCoreServer struct {
}

func (*UnimplementedPayCoreServer) Pay(context.Context, *PayReq) (*PayResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pay not implemented")
}
func (*UnimplementedPayCoreServer) Refund(context.Context, *RefundReq) (*RefundResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refund not implemented")
}

func RegisterPayCoreServer(s *grpc.Server, srv PayCoreServer) {
	s.RegisterService(&_PayCore_serviceDesc, srv)
}

func _PayCore_Pay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayCoreServer).Pay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pay_core.pay_core/Pay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayCoreServer).Pay(ctx, req.(*PayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayCore_Refund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayCoreServer).Refund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pay_core.pay_core/Refund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayCoreServer).Refund(ctx, req.(*RefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PayCore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pay_core.pay_core",
	HandlerType: (*PayCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "pay",
			Handler:    _PayCore_Pay_Handler,
		},
		{
			MethodName: "refund",
			Handler:    _PayCore_Refund_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pay_core.proto",
}
